### ISSUE TITLE
Create generic button components in Figma

### ISSUE THREAD

**Issue by Ethan-Harris07** [Pv3-Labs/gibberle#29]
## Description
Create smal/medium/large button templates for our site. Once this feature is done, anyone looking to add a button to a figma frame should be able to look up something like "Genric button small" or "Share button" in the assets folder. We want a generic button so that if we change, for example: the size/color of the original small generic button component, all other small buttons across the website change without having us to change them individually

## Acceptance Criteria
- [ ] Small, medium, and large buttons are made
- [ ] Each button has a generic text component in it
- [ ] Each button has a hover variant
- [ ] Colors used in a given button use a color from color scheme 1. To do this, when selecting the fill color, click the libraries tab and you should see colors that have names (like primary, secondary, text, accent). Choose one that makes sense
- [ ] This is all done in the figma components page and all of the generic button(s) are grouped together (select them all, right click and select group option)

## Dev Notes
- The given chakra button components may be enough (they have different sizes as well). If this is the case, just make sure the font/size inside the button is a generic text and that the button has a hover variant
- [figma component page link](https://www.figma.com/design/3FNhMXGGHrPWNaWNxGhjUE/Gibberle-Figma-(CLICK-THIS-ONE-TO-IMPLEMENT-DESIGNS)?node-id=2241-528&node-type=canvas&t=nzQfmMbXHEPK1edl-0)
- Link to the how-to-figma presentation (TODO)

## Subtasks
- [x] #26 
- [ ] Blocked by #41
