### ISSUE TITLE
Keyboard component Figma

### ISSUE THREAD

**Issue by Ethan-Harris07** [Pv3-Labs/gibberle#32]
## Description
Create a component that is an interactive keyboard in figma. This component looks like the monkeytype keboard and will be displayed in the center of the screen at the bottom.

## Acceptance Criteria
- [x] The keyboard component consists of all necessary key components (W key, A key, Space, etc)
- [x] There is an icon that the user can press to hide the keyboard
- [x] The keyboard component has a background color set (some color schemes might not have this but should have it as default as it can be removed easily)
- [x] This component is in the components page of the figma
- [x] Non key components have a hover variant (like the hide keyboard icon)
- [x] Any colors used should be a color variable in a color scheme. To access the colors, when you select the fill color, there should be a libraries tab. In the libraries tab select either background, primary, secondary, accent, text, etc)

## Dev Notes
- [Figma components page](https://www.figma.com/design/3FNhMXGGHrPWNaWNxGhjUE/Gibberle-Figma-(CLICK-THIS-ONE-TO-IMPLEMENT-DESIGNS)?node-id=2241-528&node-type=canvas&t=nzQfmMbXHEPK1edl-0)
- ![Image](https://github.com/user-attachments/assets/ae3b64dc-6111-4180-942c-b0f3dccbec42)
- If there isn't a color in the color scheme that you want that you think makes sense for the site, you can add one to the color scheme. (there is a how to for this in the color scheme page of the figma)

## Subtasks
- [x] #34
- [x] #26
