### ISSUE TITLE
Input Phrase Component Figma

### ISSUE THREAD

**Issue by Ethan-Harris07** [Pv3-Labs/gibberle#33]
## Description
This component is the blank version of the phrase and is represented as underscores separated by spaces. As the user types in their guessed phrase, they should see what they are typing and where their next typed letter should be.

## Acceptance Criteria
- [x] Good spacing: It is easily distinguishable to tell how many letters are in each word and how many words are in the phrase 
- [x] Attempt at an animation (as the user types in the phrase, animate it somehow). Original thought is to float the current underscore where the user's next typed letter will be. The animation could be just that the underscore changes color (if this is the case make it so the color fades into and out of existence)
- [x] The user is able to tell where their next typed in letter will be
- [x] A text component is made for the underscores and for letters when a user types in a guess (regular text components don't have enough spacing which means underlines are connected like this: _____, when we want: _ _ _)
- [x] Any colors used should be a color variable in a color scheme. To access the colors, when you select the fill color, there should be a libraries tab. In the libraries tab select either background, primary, secondary, accent, text, etc)
- [x] This component is in the component page of the figma

## Dev Notes
- [Figma component page](https://www.figma.com/design/3FNhMXGGHrPWNaWNxGhjUE/Gibberle-Figma-(CLICK-THIS-ONE-TO-IMPLEMENT-DESIGNS)?node-id=2241-528&node-type=canvas&t=nzQfmMbXHEPK1edl-0)
- You can search things on figma, some people have made figma boards for animations or text animation that you can look at

## Subtasks
- #26
