### ISSUE TITLE
Figma New Website Designs

### ISSUE THREAD

**Issue by Ethan-Harris07** [Pv3-Labs/gibberle#41]
## Description
Right now we have a design that looks a lot like wordle. We should really try and come up with some unique layouts. The layout should look clean and nice.

## Acceptance Criteria
- [ ] At least two different designs are shown
- [ ] The site has intractability (When the stats button/icon is pressed it shows you your career stats) 
- [ ] Any colors used should be a color variable in a color scheme. To access the colors, when you select the fill color, there should be a libraries tab. In the libraries tab select either background, primary, secondary, accent, text, etc)
- [ ] Important things like the jumbled phrase and input guessed phrase are prominent on the site. Meaning that a user can easily see them. 
- [ ] Landing page, stats, and how to play all have designs
- [ ] This is done in the Rough Design Layout page in the figma (under the original)

## Dev Notes
- [Figmarough design layout page](https://www.figma.com/design/3FNhMXGGHrPWNaWNxGhjUE/Gibberle-Figma-(CLICK-THIS-ONE-TO-IMPLEMENT-DESIGNS)?node-id=2110-34&node-type=canvas&t=DFk5lIb6mgoAXO0E-0)
- Recommend using [Dribbble](https://dribbble.com/following) for inspiration
- The actual game page is great, don't need to change unless we want to include live stats

## Subtasks
- [x] #26 (Note: color scheme does not need to be done, just implemented)
- [ ] #51
- [ ] Figma Finalized Landing Page
- [ ] Figma Finalized Stats Page
