### ISSUE TITLE
Figma Website Icons

### ISSUE THREAD

**Issue by Ethan-Harris07** [Pv3-Labs/gibberle#42]
## Description
Icons are have the same functionality as buttons. They differ in that no text is used for an icon because the icon image is enough to explain what the functionality of the component is with no explanation. For our site we want icons that are simple and that make sense for its functionality. 

## Acceptance Criteria
- [ ] The icons chosen need no explanation for its functionality (Ex: a cogwheel usually means settings)
- [ ] All Icon components have variants for all their interactions (What happens when the icon is clicked or hovered over? Is there an animation?)
- [ ] All colors used for the icons are from the color variables from the color scheme library. (To access them, when selecting the fill color, oyu should see variable name options for things like Background, text, primary, secondary, and accent)
- [ ] All Icons are in the components page in the figma in the section labeled Icon Components

## Dev Notes
- Can search the assets for chakra implemented icons. If you use a chakra one, just copy it into the components page and re-name it to something that makes sense for our page (settings cog ex: maybe something like Gibberle settings cog") 
- [figma component page link](https://www.figma.com/design/3FNhMXGGHrPWNaWNxGhjUE/Gibberle-Figma-(CLICK-THIS-ONE-TO-IMPLEMENT-DESIGNS)?node-id=2241-528&node-type=canvas&t=nzQfmMbXHEPK1edl-0)

## Subtasks
- [ ] [One color scheme needs to be implemented](https://github.com/Pv3-Labs/gibberle/issues/26#issue-2553833636)
