### ISSUE TITLE
Input Phrase Component - In Code

### ISSUE THREAD

**Issue by Ethan-Harris07** [Pv3-Labs/gibberle#75]
## Description
With the game we need a custom text box to allow the user to input their guess for the phrase of the day. The user should be notified when their guess is correct or not correct

## Acceptance Criteria
- [ ] The user can easily tell how many characters are in each word of the phrase and how many words are in the phrase (make sure letter and space spacing is set appropriately)
- [ ] The component shows where the next typed letter will be (text cursor component)
   - On a keyboard input, the input text as well as the cursor string needs to be adjusted (look at dev notes below for further explanation
- [ ] If the guess is incorrect or not a valid guess =, the user is notified of it
- [ ] The component handles a correct guess (just make sure that when the enter key/button is pressed, it checks for the correct phrase matches the input
- [ ] Spaces are ignored: the cursor automatically jumps in between words without the user typing in a space

## Dev Notes
- [If you present the rough design in figma, the input component is in it](https://www.figma.com/design/3FNhMXGGHrPWNaWNxGhjUE/Gibberle-Figma-(CLICK-THIS-ONE-TO-IMPLEMENT-DESIGNS)?node-id=2110-34&node-type=canvas&t=fWO8jlgNwKAh9oJl-0)
- [video](https://github.com/user-attachments/assets/875b375f-7de3-42a0-880e-3feb32deec64) showing the input phrase cursor moving as the user types
- I used a monospaced font in figma so that the underscores always match the characters that will be typed
- Can line up the underscores and inputed characters by making the text be left-aligned and placing the text boxes in the same spot
- To move the cursor I made the curser be this string: "_", and on a keyboard input, just add a space in front of the underscore: " " + "_". This is also why the text needs to be monospaced otherwise spaces are different sizes then a character

## Subtasks
- [x] #33 
- [ ] #76
