### ISSUE TITLE
Mockup and Feature Design Doc for Landing Page

### ISSUE THREAD

**Issue by Ethan-Harris07** [Pv3-Labs/gibberle#87]
## Description
The landing page is the page that users are met with when they first reach our website. Here they can sign in, play the game, or get a tutorial if they want if it is the first time they are playing.

## Acceptance Criteria
- [x] Feature design doc is made for this page. It should outline how the user interacts with the page (what buttons are on it, what happens if they press it, etc)
    - Include an Image as well once the mockup is done
- [ ] Mockup is made on figma, it should use the default theme colors
    - Three buttons: Sign in, Play, and Tutorial
    - There should be a separate page for if the user has already played the game before. In this case, there should be no tutorial button
    - Play button should stand out from other button
    - Test different ways for the user to sign in (where the button is, etc)
    - [ ] Design has a mobile version design

## Dev Notes
- Mockup design should be in the Website Layout page of the [Figma](https://www.figma.com/design/3FNhMXGGHrPWNaWNxGhjUE/Gibberle-Figma-(CLICK-THIS-ONE-TO-IMPLEMENT-DESIGNS)?node-id=2110-34&node-type=canvas&t=WA4vdBIFJceUXpN5-0)
- [Feature design doc](https://docs.google.com/document/d/1bcbkr1a3ASHEmaWaRtcEmYZPR0fRRlP2FmevygEAY0s/edit?tab=t.0)
    - Note this is a different page than the previous one we had, I made a new one because I want it to look more appealing and the old one is partially outdated
    - [Old feature design](https://docs.google.com/document/d/1QrT-5Dl7TdvTfMHI8BvF3bHHdU_GD5G13h1dqisdbgE/edit?tab=t.0) doc if you want to reference it

## Subtasks
-None
