### ISSUE TITLE
Mockup and Feature Design Doc for How to Play Popup

### ISSUE THREAD

**Issue by Ethan-Harris07** [Pv3-Labs/gibberle#88]
## Description
When users are either first playing our game or need a quick refresher if they haven't played for, they are able to ask for a tutorial on how to play Gibberle. Users can get to the tutorial from either the landing page (when it is their first time playing) or when they are playing the game (hint icon)

## Acceptance Criteria
- [ ] Short and to the point, and should leave a user with no questions on how to play the game
- [x] Feature design doc is made for this page. It should outline how the user interacts with the popup (what buttons are on it, what happens if they press it, etc)
    - If we stick with the slide show design for hints, this should describe each slide, the fact that the slides automatically loop through, and the user can go in between them via a button if they choose
    - Include an Image as well once the mockup is done
- [ ] Mockup is made on figma, it should use the default theme colors
    - Is fully interactable and working
    - [ ] Design has a mobile version design

## Dev Notes
- Mockup design should be in the Website Layout page of the [Figma](https://www.figma.com/design/3FNhMXGGHrPWNaWNxGhjUE/Gibberle-Figma-(CLICK-THIS-ONE-TO-IMPLEMENT-DESIGNS)?node-id=2110-34&node-type=canvas&t=WA4vdBIFJceUXpN5-0)
- [Feature design doc](https://docs.google.com/document/d/1bcbkr1a3ASHEmaWaRtcEmYZPR0fRRlP2FmevygEAY0s/edit?tab=t.0)
    - Note this is a different page than the previous one we had, I made a new one because I want it to look more appealing and the old one is partially outdated
    - [Old feature design](https://docs.google.com/document/d/1QrT-5Dl7TdvTfMHI8BvF3bHHdU_GD5G13h1dqisdbgE/edit?tab=t.0) doc if you want to reference it

## Subtasks
- None

**Comment by DanielTran24** [comment]
Almost finished with the code but haven't started the feature design doc yet
