### ISSUE TITLE
Mockup and Feature Design Doc for Stats/Post Guess Screen

### ISSUE THREAD

**Issue by Ethan-Harris07** [Pv3-Labs/gibberle#89]
## Description
After the user finishes the game mode that they are playing, they should be met with a screen that congratulates them on guessing the word as well as a graph that shows how they compared with all people who played that day
## Acceptance Criteria
- [x] Feature design doc is made for this page. It should outline how the user interacts with the page (what buttons are on it, what happens if they press it, etc)
    - The only user interactivity is if the user wants to share their stats or if they want to see their profile/settings 
    - Include an Image as well once the mockup is done
- [ ] Mockup is made on figma, it should use the default theme colors
    - For the graph: there should be graphs for al the stats we keep track of and the user should be able to select which graph they want to see. The default should be number of guesses 
    - [ ] Design has a mobile version design

## Dev Notes
- Mockup design should be in the Website Layout page of the [Figma](https://www.figma.com/design/3FNhMXGGHrPWNaWNxGhjUE/Gibberle-Figma-(CLICK-THIS-ONE-TO-IMPLEMENT-DESIGNS)?node-id=2110-34&node-type=canvas&t=WA4vdBIFJceUXpN5-0)
- [Feature design doc](https://docs.google.com/document/d/1bcbkr1a3ASHEmaWaRtcEmYZPR0fRRlP2FmevygEAY0s/edit?tab=t.0)
    - Note this is a different page than the previous one we had, I made a new one because I want it to look more appealing and the old one is partially outdated
    - [Old feature design](https://docs.google.com/document/d/1QrT-5Dl7TdvTfMHI8BvF3bHHdU_GD5G13h1dqisdbgE/edit?tab=t.0) doc if you want to reference it

## Subtasks
-None
