### ISSUE TITLE
Mockup and Feature Design Doc for the Nav Bar

### ISSUE THREAD

**Issue by Ethan-Harris07** [Pv3-Labs/gibberle#90]
## Description
The nav bar is on the top right of the screen when the user is playing the main game. It allows the user to get a hint, see their user profile, change settings, and get a tutorial on how to play the game if they need a quick refresher

## Acceptance Criteria
- [x] Feature design doc is made for this page. It should outline how the user interacts with the page (what each icon is, what happens if they press it, etc)
    - Include an Image as well once the mockup is done
- [ ] Mockup is made on figma, it should use the default theme colors
    - Three buttons: Sign in, Play, and Tutorial
    - There should be a separate page for if the user has already played the game before. In this case, there should be no tutorial button
    - [ ] Design has a mobile version design
- All icons on the navbar:
    - Setting cog: Difficulty, accessibility (if we are doing anything for this), themes, bugs, ... and anything else you think of
        - for theme: implement at least three themes so we know if it is working
            - don't have to be polished themes, just different colors from the default
    - Hint icon: text hint (like genre) that shows up below the Gibberle text and above the jumbled phrase
    - How to play (question mark icon): brings user to how to play popup 
    - User profile icon (stats icon): Brings user to page that shows all their life time stats as a graph and other things that I cannot think of at this point in time

## Dev Notes
- The mockup may be done, if you feel the design is fine you can ignore making the mockup
- Mockup design should be in the Website Layout page of the [Figma](https://www.figma.com/design/3FNhMXGGHrPWNaWNxGhjUE/Gibberle-Figma-(CLICK-THIS-ONE-TO-IMPLEMENT-DESIGNS)?node-id=2110-34&node-type=canvas&t=WA4vdBIFJceUXpN5-0)
- [Feature design doc](https://docs.google.com/document/d/1bcbkr1a3ASHEmaWaRtcEmYZPR0fRRlP2FmevygEAY0s/edit?tab=t.0)
    - Note this is a different page than the previous one we had, I made a new one because I want it to look more appealing and the old one is partially outdated
    - [Old feature design](https://docs.google.com/document/d/1QrT-5Dl7TdvTfMHI8BvF3bHHdU_GD5G13h1dqisdbgE/edit?tab=t.0) doc if you want to reference it

## Subtasks
-None
